#!/usr/bin/env python

## TESTING
import numpy as np
import matplotlib.pyplot as plt
import os
from past.builtins import execfile

print("Running burgers_filtered")
execfile("burgers_filtered.py")
for f in os.listdir("."):
    if f.endswith(".png" or ".svg"):
        os.rename(f, "_site/plots/"+f)


with open("_site/index.html", 'w') as file:
	file.write("Done generating plots.")
print("Done generating plot scripts.")
